### ISSUE TITLE
Operator not compatible with OCP 4.12

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#27]
The patch operation expects fields that are not available in OCP 4.12, e.g. _spec.template.spec.schedulingGates_.

```
8752
- io.devjoy.gitea.k8s.gitea.GiteaDeploymentDependentResource -> io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.30.0.1:443/apis/apps/v1/namespaces/bschmeli-gitea/deployments/gitea-test?fieldManager=giteareconciler&force=true. Message: failed to create typed patch object (bschmeli-gitea/gitea-test; apps/v1, Kind=Deployment): .spec.template.spec.schedulingGates: field not declared in schema. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=failed to create typed patch object (bschmeli-gitea/gitea-test; apps/v1, Kind=Deployment): .spec.template.spec.schedulingGates: field not declared in schema, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
8753
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
8754
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
8755
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:430)
8756
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:408)
8757
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:713)
8758
at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:232)
8759
at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:237)
8760
at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:252)
8761
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1132)
8762
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:92)
8763
at io.javaoperatorsdk.operator.processing.dependent.kubernetes.KubernetesDependentResource.create(KubernetesDependentResource.java:140)
8764
at io.javaoperatorsdk.operator.processing.dependent.kubernetes.CRUDKubernetesDependentResource.create(CRUDKubernetesDependentResource.java:16)
8765
at io.javaoperatorsdk.operator.processing.dependent.AbstractDependentResource.handleCreate(AbstractDependentResource.java:114)
8766
at io.javaoperatorsdk.operator.processing.dependent.kubernetes.KubernetesDependentResource.handleCreate(KubernetesDependentResource.java:111)
8767
at io.javaoperatorsdk.operator.processing.dependent.kubernetes.KubernetesDependentResource.handleCreate(KubernetesDependentResource.java:32)
8768
at io.javaoperatorsdk.operator.processing.dependent.AbstractDependentResource.reconcile(AbstractDependentResource.java:62)
8769
at io.javaoperatorsdk.operator.processing.dependent.SingleDependentResourceReconciler.reconcile(SingleDependentResourceReconciler.java:19)
8770
at io.javaoperatorsdk.operator.processing.dependent.AbstractDependentResource.reconcile(AbstractDependentResource.java:52)
8771
at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowReconcileExecutor$NodeReconcileExecutor.doRun(WorkflowReconcileExecutor.java:115)
8772
at io.javaoperatorsdk.operator.processing.dependent.workflow.NodeExecutor.run(NodeExecutor.java:22)
8773
at java.base@17.0.9/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
8774
at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
8775
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
8776
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
8777
at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
8778
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
8779
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

**Comment by Javatar81** [comment]
The following resources have been created:

- Service 
- Secret
- Route

The following resources have **NOT** been created:

- Deployment
- PersistentVolumeClaim

**Comment by metacosm** [comment]
This might be due to an incompatibility issue at the Kubernetes level, though I do seem to recall some issues with PVC in JOSDK…

**Comment by Javatar81** [comment]
But why does the operator send a patch which seems to include all possible fields of the schema?

**Comment by metacosm** [comment]
Not sure, we'll have to look at the details. @csviri would know better.

**Comment by csviri** [comment]
It's quite strnage, we have Deployments in the E2E tests, although not on openshift. If you could create a minimalist example to reproduce would be a big help.

**Comment by Javatar81** [comment]
I can't reproduce with integration tests on an OCP 4.12 cluster. The problem occurs only when running a native build (built on OCP 4.13) of the operator on an OCP 4.12 cluster. Any ideas why?

**Comment by csviri** [comment]
Ohh that is interesting, maybe @manusa @shawkins can tell more.

**Comment by manusa** [comment]
Have you tried to serialize the sent resources to a file? 
It's weird that those fields are included, it should actually be the complete opposite (fields missing for empty arrays and such).

**Comment by Javatar81** [comment]
Not that I am aware of but I am loading manifests in the dependent resources desired state method to start from a base configuration. Then, I add / change dynamic fields.

**Comment by Javatar81** [comment]
Does not occur in this version of the operator. Tested in OCP 4.12 again wit 0.2.0.
