### ISSUE TITLE
Infinite reconcilation loop when adminUser == 'admin'

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#28]
```
2023-11-13 20:33:49,239 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-8) Setting desired Gitea service
2023-11-13 20:33:49,239 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-8) Name is example 
2023-11-13 20:33:49,248 INFO  [io.dev.git.k8s.pos.PostgresDeploymentDependentResource] (pool-18-thread-10) Setting desired Postgres deployment
2023-11-13 20:33:49,263 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-9) Setting desired Gitea config map
2023-11-13 20:33:49,263 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-9) Read app.ini. Adding configuration parameters based on Gitea resource.
2023-11-13 20:33:49,268 INFO  [io.dev.git.k8s.git.GiteaDeploymentDependentResource] (pool-18-thread-3) Setting desired Gitea deployment
2023-11-13 20:33:49,268 INFO  [io.dev.git.k8s.pos.PostgresPvcDependentResource] (pool-18-thread-5) Setting desired Postgres pvc
2023-11-13 20:33:49,283 WARN  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-7) No password available. Will set it later
2023-11-13 20:33:49,378 INFO  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-7) Secret is not yet created
2023-11-13 20:33:49,616 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Reconciling
2023-11-13 20:33:49,616 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Waiting for Gitea pod to be ready...
2023-11-13 20:35:22,571 INFO  [io.dev.git.dom.UserService] (ReconcilerExecutor-giteareconciler-115) Waiting up to 180 seconds for replicas to become ready....
2023-11-13 20:35:22,987 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Admin user created
2023-11-13 20:35:22,992 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Updating admin password in secret
2023-11-13 20:35:22,992 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) New password. Moving password to secret
2023-11-13 20:35:23,015 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Done, updating status.
2023-11-13 20:35:23,016 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Admin password changed. 
2023-11-13 20:35:23,016 INFO  [io.dev.git.dom.UserService] (ReconcilerExecutor-giteareconciler-115) Waiting up to 180 seconds for replicas to become ready....
2023-11-13 20:35:23,324 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Removing admin password because it is stored in secret admin-git-secret
2023-11-13 20:35:23,325 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Reconciling trust map
2023-11-13 20:35:23,336 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Creating trust map
2023-11-13 20:35:23,355 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-115) Need to update 
2023-11-13 20:35:23,530 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-129) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:23,534 INFO  [io.dev.git.k8s.git.GiteaServiceAccountDependentResource] (pool-18-thread-7) Setting desired Gitea service account
2023-11-13 20:35:23,539 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-129) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:23,555 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-5) Setting desired Gitea config map
2023-11-13 20:35:23,556 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-5) Read app.ini. Adding configuration parameters based on Gitea resource.
2023-11-13 20:35:23,557 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-129) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:23,558 INFO  [io.dev.git.k8s.git.GiteaRouteDependentResource] (pool-18-thread-4) Reconciling
2023-11-13 20:35:23,566 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-1) Setting desired Gitea service
2023-11-13 20:35:23,567 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-1) Name is example 
2023-11-13 20:35:23,567 INFO  [io.dev.git.k8s.pos.PostgresDeploymentDependentResource] (pool-18-thread-9) Setting desired Postgres deployment
2023-11-13 20:35:23,568 INFO  [io.dev.git.k8s.git.GiteaPvcDependentResource] (pool-18-thread-6) Setting desired Gitea pvc
2023-11-13 20:35:23,572 INFO  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-3) Token not set. Generating new token.
2023-11-13 20:35:23,579 INFO  [io.dev.git.k8s.git.GiteaDeploymentDependentResource] (pool-18-thread-7) Setting desired Gitea deployment
2023-11-13 20:35:23,622 INFO  [io.dev.git.k8s.pos.PostgresPvcDependentResource] (pool-18-thread-8) Setting desired Postgres pvc
2023-11-13 20:35:24,528 WARN  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-3) Cannot update token.
2023-11-13 20:35:24,569 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Reconciling
2023-11-13 20:35:24,570 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Waiting for Gitea pod to be ready...
2023-11-13 20:35:25,186 INFO  [io.dev.git.dom.UserService] (ReconcilerExecutor-giteareconciler-129) Waiting up to 180 seconds for replicas to become ready....
2023-11-13 20:35:25,804 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Admin user created
2023-11-13 20:35:25,815 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Updating admin password in secret
2023-11-13 20:35:25,815 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) New password. Moving password to secret
2023-11-13 20:35:25,916 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Done, updating status.
2023-11-13 20:35:25,916 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Admin password changed. 
2023-11-13 20:35:25,916 INFO  [io.dev.git.dom.UserService] (ReconcilerExecutor-giteareconciler-129) Waiting up to 180 seconds for replicas to become ready....
2023-11-13 20:35:26,361 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Removing admin password because it is stored in secret admin-git-secret
2023-11-13 20:35:26,361 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Reconciling trust map
2023-11-13 20:35:26,379 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-129) Need to update 
2023-11-13 20:35:26,447 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-giteareconciler-129) Error during event processing ExecutionScope{ resource id: ResourceID{name='example', namespace='bschmeli-test'}, version: 3121588064} failed.: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1:443/apis/devjoy.io/v1alpha1/namespaces/bschmeli-test/giteas/example. Message: Operation cannot be fulfilled on giteas.devjoy.io "example": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=devjoy.io, kind=giteas, name=example, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on giteas.devjoy.io "example": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:358)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:708)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:139)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:122)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:45)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher$CustomResourceFacade.updateResource(ReconciliationDispatcher.java:398)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.updateCustomResource(ReconciliationDispatcher.java:336)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:144)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:121)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:91)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:417)
	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1:443/apis/devjoy.io/v1alpha1/namespaces/bschmeli-test/giteas/example. Message: Operation cannot be fulfilled on giteas.devjoy.io "example": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=devjoy.io, kind=giteas, name=example, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on giteas.devjoy.io "example": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:671)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:651)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:600)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:560)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.9/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.vertx.VertxHttpRequest.lambda$null$1(VertxHttpRequest.java:122)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:444)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:708)
	at io.vertx.core.impl.EventLoopContext.lambda$execute$2(EventLoopContext.java:78)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 3 more

2023-11-13 20:35:26,495 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-131) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:26,496 INFO  [io.dev.git.k8s.git.GiteaServiceAccountDependentResource] (pool-18-thread-2) Setting desired Gitea service account
2023-11-13 20:35:26,500 INFO  [io.dev.git.k8s.git.GiteaRouteDependentResource] (pool-18-thread-10) Reconciling
2023-11-13 20:35:26,502 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-131) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:26,506 WARN  [io.dev.git.k8s.rhs.KeycloakReconcileCondition] (ReconcilerExecutor-giteareconciler-131) Keycloak will not be provided. Property sso=false, apiGroupAvailable=true, apiVersion=v1
2023-11-13 20:35:26,527 INFO  [io.dev.git.k8s.pos.PostgresPvcDependentResource] (pool-18-thread-9) Setting desired Postgres pvc
2023-11-13 20:35:26,534 INFO  [io.dev.git.k8s.git.GiteaDeploymentDependentResource] (pool-18-thread-2) Setting desired Gitea deployment
2023-11-13 20:35:26,534 INFO  [io.dev.git.k8s.git.GiteaPvcDependentResource] (pool-18-thread-6) Setting desired Gitea pvc
2023-11-13 20:35:26,540 INFO  [io.dev.git.k8s.pos.PostgresDeploymentDependentResource] (pool-18-thread-10) Setting desired Postgres deployment
2023-11-13 20:35:26,542 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-8) Setting desired Gitea config map
2023-11-13 20:35:26,543 INFO  [io.dev.git.k8s.git.GiteaConfigSecretDependentResource] (pool-18-thread-8) Read app.ini. Adding configuration parameters based on Gitea resource.
2023-11-13 20:35:26,543 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-4) Setting desired Gitea service
2023-11-13 20:35:26,543 INFO  [io.dev.git.k8s.git.GiteaServiceDependentResource] (pool-18-thread-4) Name is example 
2023-11-13 20:35:26,544 INFO  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-7) Token not set. Generating new token.
2023-11-13 20:35:27,005 WARN  [io.dev.git.k8s.git.GiteaAdminSecretDependentResource] (pool-18-thread-7) Cannot update token.
2023-11-13 20:35:27,021 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-131) Reconciling
2023-11-13 20:35:27,022 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-131) Waiting for Gitea pod to be ready...
2023-11-13 20:35:27,467 INFO  [io.dev.git.dom.UserService] (ReconcilerExecutor-giteareconciler-131) Waiting up to 180 seconds for replicas to become ready....
2023-11-13 20:35:28,343 INFO  [io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-131) Admin user created
```

**Comment by Javatar81** [comment]
If the logs show `[io.dev.git.k8s.GiteaReconciler] (ReconcilerExecutor-giteareconciler-131) Admin user created` several times, the user cannot be created because 'admin' is reserved.

**Comment by Javatar81** [comment]
We need better exec command logging. See #29.

**Comment by Javatar81** [comment]
Furthermore, we need to validate the spec.adminUser value to be != 'admin'.

**Comment by Javatar81** [comment]
Test what happens after removing all exec commands.

**Comment by Javatar81** [comment]
Infinite reconcile loop does not occur since no exec commands involved. Post start hook command fails silently.
