### ISSUE TITLE
Error calling rest client in native integration test

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#74]
`[ERROR]   GiteaReconcilerNativeIT>GiteaReconcilerIT.lambda$changeGiteaPassword$7:187 » RestClientDefinition Failed to instantiate org.openapi.quarkus.gitea_json.api.auth.AuthenticationPropagationHeadersFactory, the client header factory for org.openapi.quarkus.gitea_json.api.UserApi
`

**Comment by Javatar81** [comment]
This is because we are instantiating the services instead of using inject. We cannot use inject in native mode.

**Comment by Javatar81** [comment]
`io.devjoy.gitea.k8s.integration.GiteaOrganizationReconcilerNativeIT.deleteFullOrg -- Time elapsed: 0.577 s <<< ERROR!
org.eclipse.microprofile.rest.client.RestClientDefinitionException: Failed to instantiate org.openapi.quarkus.gitea_json.api.auth.AuthenticationPropagationHeadersFactory, the client header factory for org.openapi.quarkus.gitea_json.api.OrganizationApi
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProviders.getCustomHeadersFactory(ClientHeaderProviders.java:119)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProviders.registerHeaderFactory(ClientHeaderProviders.java:105)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProviders.registerForClass(ClientHeaderProviders.java:99)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.createProxy(ProxyInvocationHandler.java:250)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.createProxy(ProxyInvocationHandler.java:218)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:380)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:387)
	at io.devjoy.gitea.service.OrganizationService.getDynamicUrlClient(OrganizationService.java:134)
	at io.devjoy.gitea.service.OrganizationService.lambda$get$1(OrganizationService.java:54)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.devjoy.gitea.service.OrganizationService.get(OrganizationService.java:51)
	at io.devjoy.gitea.k8s.GiteaOrganizationReconcilerIT.lambda$deleteFullOrg$4(GiteaOrganizationReconcilerIT.java:112)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.InstantiationException: org.openapi.quarkus.gitea_json.api.auth.AuthenticationPropagationHeadersFactory
	at java.base/java.lang.Class.newInstance(Class.java:749)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProviders.construct(ClientHeaderProviders.java:140)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProviders.getCustomHeadersFactory(ClientHeaderProviders.java:115)
	... 18 more
Caused by: java.lang.NoSuchMethodException: org.openapi.quarkus.gitea_json.api.auth.AuthenticationPropagationHeadersFactory.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3784)
	at java.base/java.lang.Class.newInstance(Class.java:736)
	... 20 more`
